# Generated by Django 5.0.3 on 2024-03-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCampaignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignname', models.CharField(blank=True, max_length=50)),
                ('objectives', models.TextField(blank=True, max_length=10000)),
                ('budget', models.FloatField(blank=True, max_length=100000000)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age_group', models.CharField(choices=[('T', 'Teen'), ('A', 'Adult'), ('O', 'Old')], max_length=1)),
                ('location', models.CharField(choices=[('E', 'Europe'), ('U', 'USA'), ('A', 'Asia')], max_length=1)),
                ('platform', models.CharField(choices=[('F', 'Facebook'), ('I', 'Instagram'), ('X', 'X (Twitter)'), ('T', 'TikTok')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
