# Generated by Django 5.0.3 on 2024-03-26 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignmanagment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcampaignmodel',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='newcampaignmodel',
            name='platform',
        ),
        migrations.AddField(
            model_name='newcampaignmodel',
            name='age',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='newcampaignmodel',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newcampaignmodel',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newcampaignmodel',
            name='published_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newcampaignmodel',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newcampaignmodel',
            name='gender',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='newcampaignmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newcampaignmodel',
            name='location',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
