# Generated by Django 5.0.3 on 2024-03-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignmanagment', '0002_remove_newcampaignmodel_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcampaignmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
