# Generated by Django 5.0.3 on 2024-03-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignmanagment', '0002_remove_newcampaignmodel_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcampaignmodel',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
