# Generated by Django 5.0.3 on 2024-03-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignmanagment', '0003_newcampaignmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcampaignmodel',
            name='age',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='newcampaignmodel',
            name='gender',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
