# Generated by Django 5.0.3 on 2024-03-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaignmanagment', '0003_newcampaignmodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcampaignmodel',
            old_name='title',
            new_name='titlename',
        ),
    ]
