# Generated by Django 5.0.3 on 2024-03-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignmanagment', '0004_newcampaignmodel_age_newcampaignmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcampaignmodel',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newcampaignmodel',
            name='location',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='newcampaignmodel',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
