# Generated by Django 5.0.3 on 2024-03-30 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignmanagment', '0004_rename_title_newcampaignmodel_titlename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcampaignmodel',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
