# Generated by Django 5.0.3 on 2024-03-31 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('offer_description', models.TextField()),
                ('offer_type', models.CharField(choices=[('H', 'Hotel'), ('V', 'Vacations'), ('P', 'Places')], max_length=1)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('C', 'Created'), ('R', 'Running / Active'), ('F', 'Finished')], max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
