# Generated by Django 5.0.3 on 2024-03-31 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offernmanagment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_authot', to=settings.AUTH_USER_MODEL),
        ),
    ]
