# Generated by Django 5.0.3 on 2024-03-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offernmanagment', '0002_alter_offermodel_published_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='destination_place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
