# Generated by Django 5.0.3 on 2024-03-28 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_no', models.IntegerField(blank=True)),
                ('startdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('enddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('booking_type', models.CharField(blank=True, default=[('H', 'Hotel'), ('V', 'Vacations'), ('P', 'Places')], max_length=50)),
                ('place', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(blank=True)),
                ('phase', models.CharField(blank=True, default=[('C', 'Created'), ('R', 'Running / Active'), ('F', 'Finished')], max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('published_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
