# Generated by Django 5.0.3 on 2024-03-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientnmanagment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newclientmodel',
            old_name='enddate',
            new_name='end_date_client',
        ),
        migrations.RenameField(
            model_name='newclientmodel',
            old_name='startdate',
            new_name='start_date_client',
        ),
    ]
