# Generated by Django 5.0.3 on 2024-03-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientnmanagment', '0002_rename_enddate_newclientmodel_end_date_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclientmodel',
            name='end_date_client',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='newclientmodel',
            name='start_date_client',
            field=models.DateTimeField(null=True),
        ),
    ]
