# Generated by Django 5.0.3 on 2024-03-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientnmanagment', '0005_alter_newclientmodel_end_date_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newclientmodel',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='newclientmodel',
            name='phase',
        ),
    ]
